name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: macOS-latest
    timeout-minutes: 40
    needs: prepare

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Check
      if: success()
      run: ./gradlew test
      
    - name: Android Emulator Runner
      if: always()
      uses: reactivecircus/android-emulator-runner@v2.15.0
      with:
        api-level: 28
        profile: Nexus 6
        script: ./gradlew connectedCheck
        
    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: app/build/reports

    - name: Slack notification
      if: always()
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '*Build and DebugCheck*'
        channel: '#random'
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
